### PR TITLE
[luksopenswaphookcfg] Port to C++

### LINKED ISSUE #1659: Btrfs Encrypted with small or big swap - partitioning automatically - error message
btrfs-error
Failed to open key file.
ERROR: resume: hibernation device ... not found

Calamares version : v3.2.38
Calamares config : v21.03.11
https://github.com/arcolinux/arco-calamares-config/releases/tag/21.03.11
ArcoLinux version : 21.03.11
https://github.com/arcolinux/arcolinux-iso/releases/tag/21.03.11
mkinitcpio-openswap version : 0.1.0-3
Package list : https://pastebin.com/uR6F5CSq
1 Probe link hardware and software overview : https://linux-hardware.org/?probe=79e3573fed
2 Probe link hardware and software overview : https://linux-hardware.org/?probe=d91551dac1

We do however boot up and we have a working system. Working on it now. See for more info in the probe link number 1.

Gparted

gparted

Lsblk
lsblk

Lsblk -f
lsblk-f

fstab

fstab

crypttab

cryptab

default/grub
default-grub

### PR DESCRIPTION
**Pull request by adriaandegroot**
This is a C++ port of the existing Python module. It picks up the btrfs fixes for enabling swap.

FIXES #1659 #1644

### CODE REVIEW

**Comment by adriaandegroot** [comment]
@dalto8 @LordTermor if you would take a look, please. (Especially dalto, since the Python-module-fix for btrfs swap came from them).

File: src/modules/luksopenswaphookcfg/LOSHJob.cpp [hunk 1]
```diff
@@ -0,0 +1,187 @@
...
+    {
+        int slashCount = 0;
+        while ( slashCount < btrfsRootSubvolume.length() && btrfsRootSubvolume[ slashCount ] == '/' )
+        {
+            slashCount++;
+        }
+        if ( slashCount > 0 )
+        {
+            btrfsRootSubvolume.remove( 0, slashCount );
+        }
```
Comment (dalto8) [inline src/modules/luksopenswaphookcfg/LOSHJob.cpp]: Is there a reason this is being done in such a verbose way?

It seems like something like `btrfsRootSubvolume.remove( QRegExp( "^[/]*" ) );` would be more concise and readable.

File: src/modules/luksopenswaphookcfg/Tests.cpp [hunk 2]
```diff
@@ -0,0 +1,247 @@
...
+    QTest::newRow( "comment-space-eq" ) << QStringLiteral( "# Check that a = b" ) << QString();
+
+
+    QTest::newRow( "assignment1" ) << QStringLiteral( "a=1" ) << QStringLiteral( "a" );
+    QTest::newRow( "assignment2" ) << QStringLiteral( "a = 1" ) << QStringLiteral( "a" );
+    QTest::newRow( "assignment3" ) << QStringLiteral( "#   a=1" ) << QStringLiteral( "a" );
+    QTest::newRow( "assignment4" ) << QStringLiteral( "cows   = 12" ) << QStringLiteral( "cows" );
+    QTest::newRow( "assignment5" ) << QStringLiteral( "#   # cows=1" ) << QStringLiteral( "cows" );
+    QTest::newRow( "assignment6" ) << QStringLiteral( "# moose='cool'  # not cows" ) << QStringLiteral( "moose" );
+    QTest::newRow( "assignment7" ) << QStringLiteral( " moose=cows=42" ) << QStringLiteral( "moose" );
```
Comment (dalto8) [inline src/modules/luksopenswaphookcfg/Tests.cpp:75]: The default file uses this form for a commented assignment `#a=blah`, it might be a good to have a test case for that.

**Review by dalto8 — COMMENTED** [review]
Looks good to me.

I added a couple of minor comments.

File: src/modules/luksopenswaphookcfg/LOSHJob.cpp (hunk 1 above)
Comment (kkofler) [reply src/modules/luksopenswaphookcfg/LOSHJob.cpp]: `"^/*"` without the brackets should be enough, and also, `QRegExp` is deprecated in favor of `QRegularExpression`.

Comment (adriaandegroot) [reply src/modules/luksopenswaphookcfg/LOSHJob.cpp]: I'm not immediately convinced that "I know, I'll use a RegExp!" is an improvement in readability. I've taken a slightly different tack, since I'm somewhat surprised at QString lacking an `lstrip()` and `rstrip()` equivalent. I've bunged it into libcalamares as `removeLeading(btrfsRootSubvolume, '/')`.

Comment (adriaandegroot) [reply src/modules/luksopenswaphookcfg/LOSHJob.cpp]: .. we can argue over the implementation there, but `removeLeading` is a more meaningful name than `"^/*"`

File: src/modules/luksopenswaphookcfg/Tests.cpp (hunk 2 above)
Comment (adriaandegroot) [reply src/modules/luksopenswaphookcfg/Tests.cpp:75]: I've added tests for that form as well.
